import type { PracticeDifficulty, PracticeTopic } from './content';

export type RoadmapTrack = 'algorithms' | 'system-design';
export type SystemDesignTopic = 'requirements' | 'storage' | 'caching' | 'messaging' | 'reliability' | 'consistency' | 'security' | 'observability';
export type RoadmapTopic = PracticeTopic | SystemDesignTopic;

export type RoadmapQuestion = {
  id: string;
  track: RoadmapTrack;
  topic: RoadmapTopic;
  level: PracticeDifficulty;
  title: string;
  prompt: string;
  example: string;
  focus: string;
  practiceItemId?: string;
  approach: RegExp[];
  edgeCase: RegExp[];
  complexity: RegExp[];
};

export const roadmapTopics: { id: RoadmapTopic; track: RoadmapTrack; title: string; description: string }[] = [
  { id: 'hashing', track: 'algorithms', title: 'Hash maps', description: 'Remember values and counts for fast lookups.' },
  { id: 'sliding-window', track: 'algorithms', title: 'Sliding window', description: 'Keep useful state while a range moves.' },
  { id: 'two-pointers', track: 'algorithms', title: 'Two pointers', description: 'Use ordering to guide movement through data.' },
  { id: 'stacks', track: 'algorithms', title: 'Stacks', description: 'Resolve the most recent unfinished work first.' },
  { id: 'queues', track: 'algorithms', title: 'Queues', description: 'Process ready work in arrival order.' },
  { id: 'trees', track: 'algorithms', title: 'Trees', description: 'Break branching problems into smaller subtrees.' },
  { id: 'graphs', track: 'algorithms', title: 'Graphs', description: 'Explore connections without repeating work.' },
  { id: 'dynamic-programming', track: 'algorithms', title: 'Dynamic programming', description: 'Reuse answers to overlapping subproblems.' },
  { id: 'requirements', track: 'system-design', title: 'Requirements and capacity', description: 'Turn product goals and scale assumptions into design constraints.' },
  { id: 'storage', track: 'system-design', title: 'Data and storage', description: 'Choose data models and stores from access patterns.' },
  { id: 'caching', track: 'system-design', title: 'Caching and delivery', description: 'Reduce latency and origin load while managing freshness.' },
  { id: 'messaging', track: 'system-design', title: 'Messaging and queues', description: 'Decouple work and handle asynchronous delivery.' },
  { id: 'reliability', track: 'system-design', title: 'Reliability', description: 'Keep services useful through faults and recovery.' },
  { id: 'consistency', track: 'system-design', title: 'Consistency and coordination', description: 'Choose ordering and correctness guarantees deliberately.' },
  { id: 'security', track: 'system-design', title: 'Security and privacy', description: 'Protect identities, data, and privileged operations.' },
  { id: 'observability', track: 'system-design', title: 'Observability and operations', description: 'Detect, explain, and respond to production behavior.' },
];

export const roadmapLevels: PracticeDifficulty[] = ['foundation', 'intermediate', 'advanced'];

export const roadmapQuestions: RoadmapQuestion[] = [
  { track: 'algorithms', id: 'hash-pair', topic: 'hashing', level: 'foundation', title: 'Pair with target', prompt: 'Given an unsorted list and a target, find two distinct positions whose values sum to the target.', example: '[4, 7, 1, 9], target 8 → positions 1 and 2', focus: 'Explain the lookup, its order, an edge case, and the cost.', practiceItemId: 'pair-with-target-v1', approach: [/map|dictionary|hash/i, /target\s*(?:minus|-)\s*(?:the\s+)?(?:current\s+)?value|complement/i, /(?:check|look\s*up|find)[\s\S]*(?:before|then)[\s\S]*(?:store|insert|add)|(?:check|look\s*up|find)[\s\S]*(?:map|dictionary)/i], edgeCase: [/same (?:index|position|element)|distinct|duplicate/i], complexity: [/O\(n\)/i, /O\(n\)\s*(?:extra\s+)?(?:space|memory)|space[\s\S]*O\(n\)/i] },
  { track: 'algorithms', id: 'hash-unique', topic: 'hashing', level: 'intermediate', title: 'First unique value', prompt: 'Return the first position whose value occurs exactly once, or -1 if none exists.', example: '[9, 4, 9, 6, 4] → 3', focus: 'Show how counting and original order work together.', practiceItemId: 'first-unique-index-v1', approach: [/map|dictionary|frequency|count/i, /(?:second|again|another|two)[\s\S]*(?:pass|scan|loop)|(?:count|frequenc)[\s\S]*(?:then|after)[\s\S]*(?:scan|iterate)/i], edgeCase: [/no (?:unique|single)|none|-1/i], complexity: [/O\(n\)/i] },
  { track: 'algorithms', id: 'hash-consecutive', topic: 'hashing', level: 'advanced', title: 'Longest consecutive run', prompt: 'Find the length of the longest run of consecutive integers in an unsorted list without sorting.', example: '[100, 4, 200, 1, 3, 2] → 4', focus: 'Explain why a run is expanded only from its first number.', approach: [/set|hash/i, /(?:start|beginning|first)[\s\S]*(?:predecessor|previous|minus one|[-−] 1)|(?:predecessor|previous|minus one)[\s\S]*(?:start|beginning)/i, /(?:extend|walk|grow|count)[\s\S]*(?:next|consecutive|successor)/i], edgeCase: [/duplicate|empty|negative/i], complexity: [/O\(n\)/i] },

  { track: 'algorithms', id: 'window-sum', topic: 'sliding-window', level: 'foundation', title: 'Maximum fixed window', prompt: 'Find the largest sum of any contiguous window of size k.', example: '[2, 1, 5, 1, 3, 2], k 3 → 9', focus: 'Explain initialization and each constant-time update.', practiceItemId: 'max-window-sum-v1', approach: [/first|initial/i, /sum/i, /(?:subtract|remove)[\s\S]*(?:leav|outgoing)|(?:leav|outgoing)[\s\S]*(?:subtract|remove)/i, /(?:add)[\s\S]*(?:enter|incoming)|(?:enter|incoming)[\s\S]*(?:add)/i], edgeCase: [/k\s*=\s*1|size one|whole list|k equals|negative/i], complexity: [/O\(n\)/i, /O\(1\)\s*(?:space|memory)|space[\s\S]*O\(1\)/i] },
  { track: 'algorithms', id: 'window-unique', topic: 'sliding-window', level: 'intermediate', title: 'Longest distinct substring', prompt: 'Find the length of the longest substring with no repeated character.', example: '"abcabcbb" → 3', focus: 'Explain when and how the left boundary moves.', approach: [/window|left|right/i, /set|map|last seen/i, /repeat|duplicate/i, /(?:move|advance|shrink)[\s\S]*(?:left|start)/i], edgeCase: [/empty|all (?:same|unique)|repeat/i], complexity: [/O\(n\)/i] },
  { track: 'algorithms', id: 'window-minimum', topic: 'sliding-window', level: 'advanced', title: 'Smallest covering substring', prompt: 'Find the shortest substring of s containing every character of t with the required frequencies.', example: 's="ADOBECODEBANC", t="ABC" → "BANC"', focus: 'Explain frequency counts, expansion, and safe shrinking.', approach: [/count|frequency|map/i, /(?:expand|move)[\s\S]*(?:right|end)/i, /(?:shrink|move)[\s\S]*(?:left|start)/i, /valid|cover|satisf/i], edgeCase: [/duplicate|repeated|impossible|missing/i], complexity: [/O\(n\)|O\(\|s\|\s*\+\s*\|t\|\)/i] },

  { track: 'algorithms', id: 'pointer-pair', topic: 'two-pointers', level: 'foundation', title: 'Pair in a sorted list', prompt: 'Find two positions in a sorted list whose values sum to a target.', example: '[1, 2, 4, 7], target 9 → positions 1 and 3', focus: 'Explain the direction chosen after comparing each sum.', practiceItemId: 'two-sum-window-v1', approach: [/left|start/i, /right|end/i, /(?:small|less)[\s\S]*(?:left|forward)|(?:left|forward)[\s\S]*(?:small|less)/i, /(?:large|greater)[\s\S]*(?:right|back)|(?:right|back)[\s\S]*(?:large|greater)/i], edgeCase: [/same (?:position|index)|meet|no pair|duplicate/i], complexity: [/O\(n\)/i, /O\(1\)\s*(?:space|memory)|space[\s\S]*O\(1\)/i] },
  { track: 'algorithms', id: 'pointer-dedupe', topic: 'two-pointers', level: 'intermediate', title: 'Remove sorted duplicates', prompt: 'Modify a sorted array in place so each distinct value appears once; return the new length.', example: '[1, 1, 2, 2, 3] → length 3, prefix [1, 2, 3]', focus: 'Explain read and write pointers and the first element.', approach: [/read|scan/i, /write|slow/i, /different|new|distinct|unique/i], edgeCase: [/empty|single|all (?:same|duplicate)/i], complexity: [/O\(n\)/i, /O\(1\)\s*(?:space|memory)|space[\s\S]*O\(1\)/i] },
  { track: 'algorithms', id: 'pointer-water', topic: 'two-pointers', level: 'advanced', title: 'Trapped rainwater', prompt: 'Given bar heights, calculate trapped water in linear time with constant extra space.', example: '[0, 1, 0, 2, 1, 0, 1, 3] → 5', focus: 'Explain why the lower side can be finalized.', approach: [/left/i, /right/i, /(?:left|right)\s*max|max(?:imum)?[\s\S]*(?:left|right)/i, /(?:lower|smaller)[\s\S]*(?:side|height|boundary)/i], edgeCase: [/empty|short|monotonic|no water/i], complexity: [/O\(n\)/i, /O\(1\)\s*(?:space|memory)|space[\s\S]*O\(1\)/i] },

  { track: 'algorithms', id: 'stack-brackets', topic: 'stacks', level: 'foundation', title: 'Balanced brackets', prompt: 'Check whether (), [], and {} are correctly nested.', example: '"{[()]}" → true; "([)]" → false', focus: 'Explain the stack and both failure conditions.', practiceItemId: 'balanced-brackets-v1', approach: [/stack/i, /push[\s\S]*(?:open|left)|(?:open|left)[\s\S]*push/i, /(?:pop|top)[\s\S]*(?:clos|match)|(?:clos|match)[\s\S]*(?:pop|top)/i], edgeCase: [/empty stack|unmatched|mismatch/i], complexity: [/O\(n\)/i] },
  { track: 'algorithms', id: 'stack-next', topic: 'stacks', level: 'intermediate', title: 'Next greater value', prompt: 'For each number, find the next number to its right that is greater, or -1.', example: '[2, 1, 4, 3] → [4, 4, -1, -1]', focus: 'Explain what indices wait on the monotonic stack.', approach: [/stack/i, /(?:decreasing|monotonic)/i, /(?:pop|resolve)[\s\S]*(?:greater|larger)/i], edgeCase: [/-1|no greater/i], complexity: [/O\(n\)/i] },
  { track: 'algorithms', id: 'stack-histogram', topic: 'stacks', level: 'advanced', title: 'Largest histogram rectangle', prompt: 'Find the maximum rectangle area under adjacent histogram bars.', example: '[2, 1, 5, 6, 2, 3] → 10', focus: 'Explain when a bar is popped and how width is computed.', approach: [/stack/i, /(?:smaller|lower)[\s\S]*(?:pop|height)|(?:pop)[\s\S]*(?:smaller|lower)/i, /width|boundary/i, /area/i], edgeCase: [/end|sentinel|flush|empty/i], complexity: [/O\(n\)/i] },

  { track: 'algorithms', id: 'queue-average', topic: 'queues', level: 'foundation', title: 'Moving average stream', prompt: 'After each incoming number, return the average of the most recent k numbers.', example: 'k=3, add 1, 10, 3, 5 → 1, 5.5, 4.67, 6', focus: 'Explain the queue and running sum.', approach: [/queue|deque/i, /sum/i, /(?:remove|evict|dequeue)[\s\S]*(?:old|front)|(?:old|front)[\s\S]*(?:remove|evict|dequeue)/i], edgeCase: [/fewer|before|less than k|initial/i], complexity: [/O\(1\)/i] },
  { track: 'algorithms', id: 'queue-levels', topic: 'queues', level: 'intermediate', title: 'Tree level order', prompt: 'Return the values of a binary tree grouped by depth.', example: '[3, 9, 20, null, null, 15, 7] → [[3], [9, 20], [15, 7]]', focus: 'Explain how each level is bounded in the queue.', approach: [/queue/i, /(?:level|layer)[\s\S]*(?:size|length|count)|(?:size|length|count)[\s\S]*(?:level|layer)/i, /child|children/i], edgeCase: [/empty|null/i], complexity: [/O\(n\)/i] },
  { track: 'algorithms', id: 'queue-order', topic: 'queues', level: 'advanced', title: 'Prerequisite task order', prompt: 'Return a valid order for tasks with prerequisites, or report that none exists.', example: 'A→C, B→C → [A, B, C]', focus: 'Explain indegrees, the ready queue, and cycle detection.', practiceItemId: 'task-order-v1', approach: [/indegree|prerequisite count/i, /queue/i, /(?:decrement|reduce|subtract)[\s\S]*(?:dependent|neighbor|count)/i], edgeCase: [/cycle|not all|every task|all tasks/i], complexity: [/O\(V\s*\+\s*E\)|O\(tasks\s*\+\s*dependencies\)/i] },

  { track: 'algorithms', id: 'tree-depth', topic: 'trees', level: 'foundation', title: 'Maximum depth', prompt: 'Return the maximum number of nodes on a root-to-leaf path.', example: '[3, 9, 20, null, null, 15, 7] → 3', focus: 'Explain the empty-node base case and recurrence.', practiceItemId: 'tree-max-depth-v1', approach: [/recurs|left child|left subtree/i, /right child|right subtree/i, /(?:max|larger)[\s\S]*(?:depth|left|right)/i], edgeCase: [/empty|null[\s\S]*(?:0|zero)|(?:0|zero)[\s\S]*empty/i], complexity: [/O\(n\)/i] },
  { track: 'algorithms', id: 'tree-path', topic: 'trees', level: 'intermediate', title: 'Root-to-leaf path sum', prompt: 'Determine whether some root-to-leaf path sums to a target.', example: 'root 5 with child 4 and leaf 8, target 17 → true', focus: 'Explain remaining target and why the endpoint must be a leaf.', approach: [/recurs|dfs|travers/i, /(?:subtract|remaining)[\s\S]*(?:target|sum)|(?:target|sum)[\s\S]*(?:subtract|remaining)/i, /leaf/i], edgeCase: [/empty|null|negative/i], complexity: [/O\(n\)/i] },
  { track: 'algorithms', id: 'tree-ancestor', topic: 'trees', level: 'advanced', title: 'Lowest common ancestor', prompt: 'Find the lowest node containing both target nodes in its subtrees of a general binary tree.', example: 'In a tree rooted at 3, targets 5 and 1 → 3', focus: 'Explain what each recursive call returns and when answers combine.', approach: [/recurs|dfs/i, /left/i, /right/i, /(?:both|two)[\s\S]*(?:found|non-null|return)/i], edgeCase: [/one target|itself|ancestor|missing/i], complexity: [/O\(n\)/i] },

  { track: 'algorithms', id: 'graph-islands', topic: 'graphs', level: 'foundation', title: 'Count islands', prompt: 'Count connected groups of land in a grid using four-directional neighbors.', example: '[[1,1,0],[0,1,0],[1,0,1]] → 3', focus: 'Explain search starts, visited state, and counting.', practiceItemId: 'island-count-v1', approach: [/grid|cell/i, /dfs|bfs|flood|search/i, /visited|mark/i, /count|island/i], edgeCase: [/water|empty|diagonal/i], complexity: [/O\(rows\s*\*\s*cols\)|O\(m\s*\*\s*n\)/i] },
  { track: 'algorithms', id: 'graph-shortest', topic: 'graphs', level: 'intermediate', title: 'Shortest unweighted path', prompt: 'Find the fewest edges from a start vertex to a target in an unweighted graph.', example: 'A—B—D and A—C—D → distance 2', focus: 'Explain why the first target found is shortest.', approach: [/bfs|breadth/i, /queue/i, /visited/i, /level|distance/i], edgeCase: [/unreachable|same (?:start|vertex)|no path/i], complexity: [/O\(V\s*\+\s*E\)/i] },
  { track: 'algorithms', id: 'graph-cycle', topic: 'graphs', level: 'advanced', title: 'Directed cycle detection', prompt: 'Decide whether a directed graph contains a cycle.', example: 'A→B→C→A → true', focus: 'Distinguish the active recursion path from fully visited nodes.', approach: [/dfs|depth/i, /(?:active|visiting|gray|recursion stack)/i, /(?:done|visited|black|completed)/i], edgeCase: [/back edge|self.loop|disconnected/i], complexity: [/O\(V\s*\+\s*E\)/i] },

  { track: 'algorithms', id: 'dp-stairs', topic: 'dynamic-programming', level: 'foundation', title: 'Climbing stairs', prompt: 'Count ways to climb n steps when each move is one or two steps.', example: 'n=4 → 5 ways', focus: 'Explain the recurrence and its base cases.', practiceItemId: 'climb-stairs-v1', approach: [/previous two|last two|n\s*-\s*1[\s\S]*n\s*-\s*2/i, /add|sum/i], edgeCase: [/zero|0|one|1/i], complexity: [/O\(n\)/i] },
  { track: 'algorithms', id: 'dp-robber', topic: 'dynamic-programming', level: 'intermediate', title: 'House robber', prompt: 'Maximize the sum of nonadjacent house values.', example: '[2, 7, 9, 3, 1] → 12', focus: 'Explain take versus skip for each house.', approach: [/take|rob/i, /skip|leave/i, /(?:previous|prior|two back|i\s*-\s*2)/i, /max|larger/i], edgeCase: [/empty|single|negative/i], complexity: [/O\(n\)/i] },
  { track: 'algorithms', id: 'dp-coins', topic: 'dynamic-programming', level: 'advanced', title: 'Minimum coins', prompt: 'Find the minimum coins for a target amount, or -1 when impossible.', example: 'coins [1, 3, 4], amount 6 → 2', focus: 'Explain the table, transition, and unreachable state.', practiceItemId: 'coin-change-lite-v1', approach: [/table|array|dp/i, /(?:each|every)[\s\S]*amount/i, /(?:each|every|try)[\s\S]*coin/i, /min|smallest|best/i], edgeCase: [/unreachable|impossible|-1/i], complexity: [/O\((?:amount\s*\*\s*coins|coins\s*\*\s*amount)\)/i] },

  { track: 'system-design', id: 'sd-requirements-url', topic: 'requirements', level: 'foundation', title: 'Scope a short-link service', prompt: 'Define the functional and nonfunctional requirements for a service that creates short links and redirects readers.', example: '10M links created monthly; reads outnumber writes 100:1', focus: 'Separate product behavior, scale assumptions, and service targets.', approach: [/create|shorten/i, /redirect|read/i, /latency|availability|durab/i], edgeCase: [/expired|invalid|abuse|collision/i], complexity: [/read|write/i, /10|million|ratio|qps|requests/i] },
  { track: 'system-design', id: 'sd-requirements-chat', topic: 'requirements', level: 'intermediate', title: 'Capacity plan for group chat', prompt: 'Estimate the traffic and storage for a group chat product before choosing components.', example: '2M daily users, 40 messages per active user, seven-year retention', focus: 'Show assumptions and convert them into peak traffic and storage.', approach: [/daily|active|user/i, /message/i, /peak|qps|per second/i], edgeCase: [/attachment|large group|spike|offline/i], complexity: [/storage|bytes|gb|tb|pb/i, /bandwidth|throughput|qps/i] },
  { track: 'system-design', id: 'sd-requirements-video', topic: 'requirements', level: 'advanced', title: 'Frame a global video platform', prompt: 'Define the boundaries and capacity model for video upload, processing, and playback across regions.', example: '50M daily viewers, 500K uploads per day, adaptive bitrate playback', focus: 'Distinguish control plane, media data plane, and regional targets.', approach: [/upload/i, /transcod|process/i, /playback|stream/i, /region|global/i], edgeCase: [/viral|spike|copyright|failed upload/i], complexity: [/bandwidth|egress/i, /storage|retention/i, /latency|availability/i] },

  { track: 'system-design', id: 'sd-storage-profile', topic: 'storage', level: 'foundation', title: 'Store learner profiles', prompt: 'Design the data model and store for learner profiles with settings and progress summaries.', example: 'Profile reads on every session; settings update occasionally', focus: 'Start from keys, reads, writes, and ownership.', approach: [/user|learner.*id|key/i, /profile|settings/i, /relational|sql|document/i], edgeCase: [/delete|privacy|concurrent|missing/i], complexity: [/index/i, /read|write/i] },
  { track: 'system-design', id: 'sd-storage-feed', topic: 'storage', level: 'intermediate', title: 'Model a social feed', prompt: 'Choose storage and indexes for posts, follows, and a chronological home feed.', example: '20M users; celebrity accounts have millions of followers', focus: 'Explain the write and read access patterns before picking stores.', approach: [/post/i, /follow/i, /feed|timeline/i, /index|partition/i], edgeCase: [/celebrity|hot partition|delete|fan.?out/i], complexity: [/read|write/i, /trade.?off|fan.?out/i] },
  { track: 'system-design', id: 'sd-storage-timeseries', topic: 'storage', level: 'advanced', title: 'Store high-volume metrics', prompt: 'Design storage for billions of time-stamped metric samples with recent dashboards and long retention.', example: '2M samples/second; 30 days hot, 13 months aggregated', focus: 'Explain partitioning, compaction, and retention tiers.', approach: [/time|timestamp/i, /partition|shard/i, /aggregate|roll.?up|compact/i], edgeCase: [/late|out.of.order|hot|cardinality/i], complexity: [/retention|tier|archive/i, /throughput|samples per second|million/i] },

  { track: 'system-design', id: 'sd-cache-profile', topic: 'caching', level: 'foundation', title: 'Cache profile reads', prompt: 'Add a cache to reduce repeated profile database reads while keeping edits acceptably fresh.', example: '95% reads; profile edits should appear within one minute', focus: 'Explain cache keys, misses, writes, and expiry.', approach: [/cache/i, /key|user id/i, /miss/i, /ttl|expire|invalidate/i], edgeCase: [/stale|edit|failure|stampede/i], complexity: [/hit rate|latency|database load/i] },
  { track: 'system-design', id: 'sd-cache-cdn', topic: 'caching', level: 'intermediate', title: 'Deliver global images', prompt: 'Design image delivery through a CDN with resizing and versioned updates.', example: 'Images are immutable by version; viewers span five continents', focus: 'Explain origin protection, cache keys, and invalidation.', approach: [/cdn|edge/i, /origin|object storage/i, /cache key|version/i], edgeCase: [/purge|stale|miss|hot/i], complexity: [/hit rate|egress|latency/i] },
  { track: 'system-design', id: 'sd-cache-multilayer', topic: 'caching', level: 'advanced', title: 'Control a multi-layer cache', prompt: 'Design browser, edge, and service caches for a read-heavy API with strict update rules.', example: '99.9% reads, regional service caches, updates must converge in 10 seconds', focus: 'Explain consistency across layers and protection during misses.', approach: [/browser/i, /edge|cdn/i, /service|redis|distributed cache/i, /version|invalidate|ttl/i], edgeCase: [/stampede|thundering herd|partial failure|stale/i], complexity: [/fresh|seconds|sla|slo/i, /trade.?off/i] },

  { track: 'system-design', id: 'sd-message-email', topic: 'messaging', level: 'foundation', title: 'Queue welcome emails', prompt: 'Move welcome-email delivery out of the signup request while preventing lost work.', example: 'Signup must finish in 300 ms; email may arrive within two minutes', focus: 'Explain durable enqueue, worker acknowledgement, and retries.', approach: [/queue/i, /worker|consumer/i, /ack|acknowledge/i, /retr(?:y|ies)/i], edgeCase: [/duplicate|provider failure|poison|dead.?letter/i], complexity: [/latency|throughput|backlog/i] },
  { track: 'system-design', id: 'sd-message-orders', topic: 'messaging', level: 'intermediate', title: 'Process order events safely', prompt: 'Design an event flow that updates inventory, payment state, and notifications under at-least-once delivery.', example: 'Events may be delayed, duplicated, or delivered out of order', focus: 'Explain idempotency, ordering scope, and failure recovery.', approach: [/event|queue|stream/i, /idempoten/i, /order|sequence|partition/i], edgeCase: [/duplicate|out.of.order|partial|retry/i], complexity: [/at.least.once|exactly.once|trade.?off/i] },
  { track: 'system-design', id: 'sd-message-stream', topic: 'messaging', level: 'advanced', title: 'Build a replayable event pipeline', prompt: 'Design a multi-consumer event stream that supports replay, schema evolution, and lag isolation.', example: 'Audit, analytics, and recommendation consumers read the same events', focus: 'Explain partitions, offsets, retention, and contracts.', approach: [/partition/i, /offset|checkpoint/i, /retention|replay/i, /schema|version/i], edgeCase: [/slow consumer|lag|poison|rebalance/i], complexity: [/throughput|partition count/i, /ordering|trade.?off/i] },

  { track: 'system-design', id: 'sd-reliable-health', topic: 'reliability', level: 'foundation', title: 'Make an API survive one instance failure', prompt: 'Design a small API deployment that remains available when one application instance stops.', example: 'Three stateless instances behind a load balancer', focus: 'Explain health checks, traffic removal, and state placement.', approach: [/load balancer/i, /health check/i, /stateless|shared state/i], edgeCase: [/instance failure|restart|false positive|session/i], complexity: [/availability|recovery|seconds/i] },
  { track: 'system-design', id: 'sd-reliable-region', topic: 'reliability', level: 'intermediate', title: 'Recover from a regional outage', prompt: 'Design failover for a service with a database and a 15-minute recovery objective.', example: 'Traffic is normally served from one primary region', focus: 'Explain replication, routing, recovery objectives, and data loss.', approach: [/region/i, /replica|replication/i, /dns|routing|failover/i], edgeCase: [/split brain|stale replica|failed failover/i], complexity: [/rto|recovery time|15 minute/i, /rpo|data loss/i] },
  { track: 'system-design', id: 'sd-reliable-overload', topic: 'reliability', level: 'advanced', title: 'Control cascading overload', prompt: 'Protect a dependency chain when traffic exceeds capacity and downstream latency rises.', example: 'API → recommendation → database; traffic triples in five minutes', focus: 'Explain budgets, backpressure, degradation, and recovery.', approach: [/timeout/i, /circuit breaker|shed|backpressure/i, /retry/i, /degrad|fallback/i], edgeCase: [/retry storm|queue growth|cascad/i], complexity: [/latency budget|capacity|saturation/i, /trade.?off/i] },

  { track: 'system-design', id: 'sd-consistency-counter', topic: 'consistency', level: 'foundation', title: 'Count likes across replicas', prompt: 'Choose a consistency model for a highly available like counter.', example: 'A displayed count may lag briefly, but a user should not create duplicate likes', focus: 'Separate exact user actions from an eventually convergent total.', approach: [/unique|idempoten|user.*post/i, /eventual|converge/i, /counter|aggregate/i], edgeCase: [/duplicate|offline|conflict/i], complexity: [/availability|consistency|trade.?off/i] },
  { track: 'system-design', id: 'sd-consistency-booking', topic: 'consistency', level: 'intermediate', title: 'Prevent double booking', prompt: 'Design seat reservation so two buyers cannot purchase the same seat.', example: 'Reservations expire after five minutes if payment is incomplete', focus: 'Explain the atomic ownership transition and expiry.', approach: [/transaction|atomic|compare.and.set|lock/i, /reservation|hold/i, /expire|ttl/i], edgeCase: [/concurrent|timeout|payment failure/i], complexity: [/contention|latency|availability/i] },
  { track: 'system-design', id: 'sd-consistency-global', topic: 'consistency', level: 'advanced', title: 'Coordinate a global configuration store', prompt: 'Design globally readable configuration with ordered updates and safe rollout.', example: 'Millions of readers; fewer than 100 writes/day; stale security policy is dangerous', focus: 'Explain leaders, quorum, versioning, and rollout failure.', approach: [/leader|consensus|quorum/i, /version|revision/i, /replica|region/i], edgeCase: [/partition|stale|rollback|split brain/i], complexity: [/read latency|write latency|availability|trade.?off/i] },

  { track: 'system-design', id: 'sd-security-session', topic: 'security', level: 'foundation', title: 'Secure web sessions', prompt: 'Design login sessions for a browser application that handles private learner data.', example: 'Users sign in with email; sessions last seven days', focus: 'Explain tokens, cookie controls, expiry, and revocation.', approach: [/session|token/i, /http.?only|secure cookie/i, /expire|rotate|refresh/i], edgeCase: [/logout|stolen|revok|csrf/i], complexity: [/seven day|duration|risk|trade.?off/i] },
  { track: 'system-design', id: 'sd-security-tenant', topic: 'security', level: 'intermediate', title: 'Isolate organization data', prompt: 'Design authorization and storage boundaries for a multi-tenant learning platform.', example: 'Instructors and learners belong to one or more organizations', focus: 'Explain tenant identity, role checks, query enforcement, and audit.', approach: [/tenant|organization.*id/i, /role|permission|authorization/i, /row.level|rls|query/i], edgeCase: [/cross.tenant|admin|membership change/i], complexity: [/audit|least privilege|defense/i] },
  { track: 'system-design', id: 'sd-security-upload', topic: 'security', level: 'advanced', title: 'Secure untrusted file uploads', prompt: 'Design an upload pipeline for learner files that may be malicious or contain private data.', example: 'Files are scanned before instructors can download them', focus: 'Explain isolation, validation, scanning, access, and retention.', approach: [/object storage|quarantine/i, /scan|malware/i, /content type|size|validat/i, /signed url|authorization/i], edgeCase: [/zip bomb|scanner failure|private|timeout/i], complexity: [/retention|cost|latency|trade.?off/i] },

  { track: 'system-design', id: 'sd-observe-api', topic: 'observability', level: 'foundation', title: 'Observe an API', prompt: 'Choose logs, metrics, traces, and alerts for a learner-facing API.', example: 'The team needs to explain slow requests and error spikes', focus: 'Connect signals to user-visible behavior.', approach: [/metric/i, /log/i, /trace|request id|correlation/i], edgeCase: [/personal|secret|sensitive|cardinality/i], complexity: [/latency|error|traffic|saturation/i] },
  { track: 'system-design', id: 'sd-observe-slo', topic: 'observability', level: 'intermediate', title: 'Define service objectives', prompt: 'Define an availability and latency SLO for practice submissions and alert on meaningful burn.', example: '99.9% successful submissions; 95% complete within two seconds', focus: 'Explain indicators, windows, error budgets, and paging.', approach: [/sli|indicator|success/i, /slo|99\.9|target/i, /error budget|burn/i], edgeCase: [/dependency|maintenance|low traffic|false alert/i], complexity: [/window|day|week|month/i, /page|ticket|alert/i] },
  { track: 'system-design', id: 'sd-observe-incident', topic: 'observability', level: 'advanced', title: 'Diagnose a distributed incident', prompt: 'Design telemetry and an incident path for intermittent failures across API, queue, worker, and database.', example: 'One percent of jobs remain queued for more than ten minutes', focus: 'Explain correlation, queue health, dependency evidence, and safe response.', approach: [/correlation|trace|request id/i, /queue|lag|age|backlog/i, /database|dependency/i, /runbook|incident/i], edgeCase: [/missing telemetry|sampling|partial outage/i], complexity: [/mttr|detect|recovery/i, /alert|threshold|slo/i] },
];

export const findRoadmapQuestion = (id: string) => roadmapQuestions.find((question) => question.id === id);
